name: Build and Upload to Firebase

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout кода
        uses: actions/checkout@v3

      - name: Установка Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.3'
      
      - name: Проверка версий Flutter и Dart
        run: |
          flutter --version
          dart --version

      - name: Получение зависимостей
        run: flutter pub get

      - name: Сборка APK
        run: flutter build apk --release

      - name: Установка Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Отправка в Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --groups testers \
            --release-notes "Автоматическая сборка от ${{ github.sha }}"
